version: '3.8'

services:
  pak-fashion:
    build: .
    ports:
      - "8502:8505"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8502
    command: streamlit run src/app.py --server.port=8505 --server.address=0.0.0.0
